/*
 * Copyright 2008-2009 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Chat.java
 *
 * Created on 9-lug-2009, 19.21.09
 */

package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import net.sf.jml.MsnContact;

import net.sf.jml.MsnMessenger;
import zeusmsn.MenuContatti;

/**
 *
 * @author Francesco Lopez
 */
public class Chat extends javax.swing.JFrame {

    private MsnContact contact;

    MsnMessenger messenger;
    
    public Chat() {
        initComponents();
    }

    public Chat(String titolo, MsnContact tempContatto,MsnMessenger tempMessenger) {
        
        this();

        setTitle(titolo);
        contact = tempContatto;
        messenger = tempMessenger;

        JMenuBar menuBar = new JMenuBar();

        JMenu fileMenu = new JMenu("Conversazione");
        menuBar.add(fileMenu);

        JMenu strumentiMenu = new JMenu("Strumenti");
        menuBar.add(strumentiMenu);

        JMenuItem openItem = new JMenuItem("Invita");
        openItem.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent event)
            {

            }

        });
        fileMenu.add(openItem);

        JMenuItem open2Item = new JMenuItem("Invia File");
        open2Item.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent event)
            {
             
            }

        });
        fileMenu.add(open2Item);

        JMenuItem open3Item = new JMenuItem("Elimina Conversazione");
        open3Item.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent event)
            {

            }

        });
        fileMenu.add(open3Item);

        JMenuItem open4Item = new JMenuItem("Chiudi");
        open4Item.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent event)
            {

            }

        });
        fileMenu.add(open4Item);

        setJMenuBar(menuBar);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        externalSplit = new javax.swing.JSplitPane();
        intSplitPannelli = new javax.swing.JSplitPane();
        jtpStrumenti = new javax.swing.JTabbedPane();
        jpImmagini = new javax.swing.JPanel();
        intSplitTesti = new javax.swing.JSplitPane();
        scrollVisualizza = new javax.swing.JScrollPane();
        jtaVisualizza = new javax.swing.JTextArea();
        splitInvio = new javax.swing.JSplitPane();
        scrollInvio = new javax.swing.JScrollPane();
        jtaScrivi = new javax.swing.JTextArea();
        jpInvio = new javax.swing.JPanel();
        jbtInvia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        externalSplit.setDividerLocation(150);
        externalSplit.setDividerSize(10);

        intSplitPannelli.setDividerLocation(150);
        intSplitPannelli.setDividerSize(10);
        intSplitPannelli.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        intSplitPannelli.setBottomComponent(jtpStrumenti);

        javax.swing.GroupLayout jpImmaginiLayout = new javax.swing.GroupLayout(jpImmagini);
        jpImmagini.setLayout(jpImmaginiLayout);
        jpImmaginiLayout.setHorizontalGroup(
            jpImmaginiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jpImmaginiLayout.setVerticalGroup(
            jpImmaginiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        intSplitPannelli.setLeftComponent(jpImmagini);

        externalSplit.setLeftComponent(intSplitPannelli);

        intSplitTesti.setDividerLocation(300);
        intSplitTesti.setDividerSize(10);
        intSplitTesti.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jtaVisualizza.setColumns(20);
        jtaVisualizza.setRows(5);
        scrollVisualizza.setViewportView(jtaVisualizza);

        intSplitTesti.setTopComponent(scrollVisualizza);

        splitInvio.setDividerLocation(350);

        jtaScrivi.setColumns(20);
        jtaScrivi.setRows(5);
        scrollInvio.setViewportView(jtaScrivi);

        splitInvio.setLeftComponent(scrollInvio);

        jbtInvia.setText("Invia");
        jbtInvia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtInviaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpInvioLayout = new javax.swing.GroupLayout(jpInvio);
        jpInvio.setLayout(jpInvioLayout);
        jpInvioLayout.setHorizontalGroup(
            jpInvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInvioLayout.createSequentialGroup()
                .addComponent(jbtInvia)
                .addContainerGap(415, Short.MAX_VALUE))
        );
        jpInvioLayout.setVerticalGroup(
            jpInvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInvioLayout.createSequentialGroup()
                .addComponent(jbtInvia)
                .addContainerGap(320, Short.MAX_VALUE))
        );

        splitInvio.setRightComponent(jpInvio);

        intSplitTesti.setRightComponent(splitInvio);

        externalSplit.setRightComponent(intSplitTesti);

        externalSplit.setBounds(1, -1, 650, 450);
        desktop.add(externalSplit, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void jbtInviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtInviaActionPerformed
        // Invia il messaggio scritto dentro la finestrella di scrittura
        //switchboard.sendMessage("ciao ciao", false);
        //System.out.println("CONTATTO:" + contact.getEmail());
        messenger.sendText(contact.getEmail(), "ciao ciao");
    }//GEN-LAST:event_jbtInviaActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JSplitPane externalSplit;
    private javax.swing.JSplitPane intSplitPannelli;
    private javax.swing.JSplitPane intSplitTesti;
    private javax.swing.JButton jbtInvia;
    private javax.swing.JPanel jpImmagini;
    private javax.swing.JPanel jpInvio;
    private javax.swing.JTextArea jtaScrivi;
    private javax.swing.JTextArea jtaVisualizza;
    private javax.swing.JTabbedPane jtpStrumenti;
    private javax.swing.JScrollPane scrollInvio;
    private javax.swing.JScrollPane scrollVisualizza;
    private javax.swing.JSplitPane splitInvio;
    // End of variables declaration//GEN-END:variables

}
